### ISSUE TITLE
dereferencing references to a constant array

### ISSUE THREAD

**Issue by acuifex** [ben-sb/javascript-deobfuscator#12]
I made this different from #11 for better issue tracking
still using https://deobfuscate.io/

after evaluating other parts of an obfuscator by hand i was left with an array of strings and references to those strings:
![image](https://user-images.githubusercontent.com/46835803/150313709-34891fcb-6bac-405d-b8c9-5a641fe02c9f.png)
there can obviously be issues if this array is modified in code but i think you can check if this array is called or modified in some way

sample code:
```javascript
totaly_constant_array = ["log", "heyo"]

console[totaly_constant_array[0]](totaly_constant_array[1])
```

deobfuscated:
```javascript
totaly_constant_array = ["log", "heyo"];
console[totaly_constant_array[0]](totaly_constant_array[1]);
```

kinda expected:
```javascript
console.log("heyo");
```

**Comment by acuifex** [comment]
my bad, after looking at readme again i saw that you can prefix arrays with const.
don't know javascript very well :)

still, checking if the array is modified in code could be nice

**Comment by ben-sb** [comment]
Yeah so the deobfuscator does actually check whether arrays are modified or not (and doesn't replace them if they are), however the reason it wasn't replacing in this case was your arrays weren't variable declarations, they were just assignments to (already existing?) variables.
It should work if you make them variable declarations by prefixing them with var, const, or let.
