### ISSUE TITLE
Identifier a has already been declared

### ISSUE THREAD

**Issue by Zimehx** [ben-sb/javascript-deobfuscator#13]
Im trying to deobfuscate pretty big code what would be the cause behind this error?

![image](https://user-images.githubusercontent.com/49727508/152013154-35fbc639-8152-4b29-bff1-2b90440f14f1.png)

**Comment by Zimehx** [comment]
https://pastebin.com/prmKJqsZ

Additional info:
- Its made in vue
- Theres another js file connected to it

**Comment by ben-sb** [comment]
Fixed in 372ef7e
