### ISSUE TITLE
Not working for this type of obfuscateion!

### ISSUE THREAD

**Issue by softwebtuts** [ben-sb/javascript-deobfuscator#14]
I am having a js code obfuscated in a different type which isn't supported in this tool. Look at this code [here](https://www.nike.com/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/p.js)

**Comment by ben-sb** [comment]
Hi, that script is obfuscated using [obfuscator.io](https://obfuscator.io/)
Also it is an anti-bot script meant to prevent bad actors so I can't help you too much, but I can give some non-specific hints :)

You can remove string obfuscation like this using [Function Evaluation](https://github.com/ben-sb/javascript-deobfuscator#function-evaluation) on the string decoder function however be aware you may have to remove any anti-tamper checks that occur in that function.
