### ISSUE TITLE
These things

### ISSUE THREAD

**Issue by hKQwHW** [ben-sb/javascript-deobfuscator#22]
```js
var a2_0x313fb4 = a2_0x20b6;
(function (shailoh, obai) {
  var vanner = a2_0x20b6;
  while (true) {
    try {
      var shacoyia = parseInt(vanner(336)) * -parseInt(vanner(369)) + parseInt(vanner(504)) * parseInt(vanner(455)) + -parseInt(vanner(364)) * -parseInt(vanner(529)) + -parseInt(vanner(331)) + -parseInt(vanner(334)) + parseInt(vanner(388)) + parseInt(vanner(374)) * parseInt(vanner(489));
      if (shacoyia === obai) break; else shailoh.push(shailoh.shift());
    } catch (zafina) {
      shailoh.push(shailoh.shift());
    }
  }
}(a2_0x3004, 451175));
```

It creates a function that calls itself, which then runs a for loop, which checks if two numbers equal each other (they always do), then breaks off. Can we detect these and cut them off? They're useless and confusing.

Also, can we try to find a way to simplify these `parseInt` things?

**Comment by ben-sb** [comment]
That looks like obfuscator.io string array rotating, this repo is meant to be general rather than targeting a specific obfuscator so removing those isn't a good fit. You will likely find more success with a project targeted towards that obfuscator such as https://github.com/relative/synchrony

**Comment by hKQwHW** [comment]
Alright, got it
