### ISSUE TITLE
Function executor does not deal with array of literals and deletes code even if no replacement is found

### ISSUE THREAD

**Issue by canpadawan** [ben-sb/javascript-deobfuscator#33]
The following snippet does not simplify
```js
function _0x1661() {
    "#execute";
    return ["str1", "str2"];
}
const foo = _0x1661()[0];
```

[FunctionExecutor.replaceFunctionCalls()](https://github.com/ben-sb/javascript-deobfuscator/blob/master/src/modifications/execution/functionExecutor.ts#L126) tries to replace the call by a literal value and fails (since we have a table of literals), so nothing gets replaced in the foo assigment (and cannot be simplified further).

The output is also not sound since the function is removed and the code can no longer be executed. Output is:
```js
const foo = _0x1661()[0];
```

I don't know much about javascript, so there might be good reasons for not handling this. What you think?

**Comment by ben-sb** [comment]
Should be sorted in 7b2a9ee
