### ISSUE TITLE
js-deobfuscator: command not found

### ISSUE THREAD

**Issue by indexofrefraction** [ben-sb/javascript-deobfuscator#46]
`npm install --global js-deobfuscator`
.. seems to work fine ... but, then on trying ... 
`js-deobfuscator`
**-bash: js-deobfuscator: command not found**
(macOS 11)

**Comment by bfontaine** [comment]
Indeed, the npm package doesn’t define any executable: https://www.npmjs.com/package/js-deobfuscator?activeTab=code

**Comment by RandomStrangerOnTheInternet** [comment]
How would one be able to run this then, or is the README.md incorrect?

**Comment by bfontaine** [comment]
@RandomStrangerOnTheInternet the README is incorrect. You might want to try with the [online version](https://deobfuscate.io/).

**Comment by indexofrefraction** [comment]
well ... the doc/readme has an example for using the CLI tool ...
