### ISSUE TITLE
unnecessary freezing after pasting large code into textarea

### ISSUE THREAD

**Issue by spiderwebdesign** [ben-sb/javascript-deobfuscator#49]
on www.deobfuscator.io there's an unnecessary delay between pasting the code and launching the dialog box.

You could use:
        launchModal(message);
        setTimeout(function() { processData(thisData) }, 10);

This would launch the modal immediately and then wait 10ms before processing the data so there's no delay between Ctrl+V and launching the modal.

**Comment by ben-sb** [comment]
Which dialog box are you referring to?

**Comment by spiderwebdesign** [comment]
![Screenshot 2023-11-23 6 53 49 PM](https://github.com/ben-sb/javascript-deobfuscator/assets/6825556/0d9d5ee0-9ab7-4976-bfef-d9898d7b06da)

You can see an example of the method I described being used at www.mylottomoney.com
I launch the dialog before loading and processing the data.

**Comment by ben-sb** [comment]
The deobfuscation starts immediately when the button is clicked and that popup should be shown asynchronously, if there's a delay in the output code appearing it's due to how long the deobfuscation process is taking
