### ISSUE TITLE
Uncaught Error: Failed to find scope for node FunctionBody

### ISSUE THREAD

**Issue by 0xdevalias** [ben-sb/javascript-deobfuscator#54]
Using the following code in the web version, I get this error, which seems to be related to the 'Replace Proxy Functions' option:

[WiNOMy0.js.txt](https://github.com/ben-sb/javascript-deobfuscator/files/15342370/WiNOMy0.js.txt)

```
Uncaught Error: Failed to find scope for node FunctionBody
    at k.enter (main.js:2:686793)
    at k.__execute (main.js:2:6811)
    at k.traverse (main.js:2:7742)
    at Object.j [as traverse] (main.js:2:557)
    at d.replaceProxyFunctionUsages (main.js:2:686703)
    at k.enter (main.js:2:687057)
    at k.__execute (main.js:2:6811)
    at k.traverse (main.js:2:7742)
    at Object.j [as traverse] (main.js:2:557)
    at d.replaceProxyFunctionUsages (main.js:2:686703)
```

**Comment by ben-sb** [comment]
That bug should be fixed in e22766d6df3093e23f04009cf4a1de142b1d2347

Your script looks like it needs a specific deobfuscator though, this project probably won't do much on it

**Comment by 0xdevalias** [comment]
> That bug should be fixed in [e22766d](https://github.com/ben-sb/javascript-deobfuscator/commit/e22766d6df3093e23f04009cf4a1de142b1d2347)

@ben-sb Thanks for that :) Is that fix pushed to https://deobfuscate.io/ yet? If so, I'm not sure it worked, as I'm still seeing the error:

> Your script looks like it needs a specific deobfuscator though, this project probably won't do much on it

@ben-sb Yeah, I suspected that would be the case as well, but was curious to see what the output would look like all the same.

**Comment by ben-sb** [comment]
You're correct, I'd forgotten to propagate the changes to the site. Should be deployed now

**Comment by 0xdevalias** [comment]
> Should be deployed now

@ben-sb Thanks :) Can confirm that it seems to work now!
