### ISSUE TITLE
Variable names, lambda functions, and executing safe javascript

### ISSUE THREAD

**Issue by hackerb9** [ben-sb/javascript-deobfuscator#6]
Thank you for this useful tool.

I have been receiving phishing/spam messages with IP addresses in the Russian Federation (e.g., `3260518168///sh.php`) that redirect to a page with the following Javascript:

```javascript
var _0x45a3=['href','310326TemamY','$1//$2','3789jqLAjI','201260CufYBR','includes','location','624856ogdMrz','28pRWhXX','10734yvtFqz','352RuMMpQ','1339PvpRAh','392868PctkdY','indexOf','596BmZxvY'];var _0x5ce7=function(_0x34bb17,_0x37718d){_0x34bb17=_0x34bb17-0x1b8;var _0x45a37a=_0x45a3[_0x34bb17];return _0x45a37a;};var _0x3c82e1=_0x5ce7;(function(_0x4279be,_0x4a014c){var _0x2ec4e6=_0x5ce7;while(!![]){try{var _0xe2f92d=-parseInt(_0x2ec4e6(0x1c4))+parseInt(_0x2ec4e6(0x1c2))*-parseInt(_0x2ec4e6(0x1bf))+-parseInt(_0x2ec4e6(0x1c0))+parseInt(_0x2ec4e6(0x1bc))*parseInt(_0x2ec4e6(0x1bd))+parseInt(_0x2ec4e6(0x1bb))+-parseInt(_0x2ec4e6(0x1b8))+parseInt(_0x2ec4e6(0x1c6))*parseInt(_0x2ec4e6(0x1be));if(_0xe2f92d===_0x4a014c)break;else _0x4279be['push'](_0x4279be['shift']());}catch(_0x1227cb){_0x4279be['push'](_0x4279be['shift']());}}}(_0x45a3,0x87e5e));var params='lptoken=16bb40f2638560276692';params!=''&&(window[_0x3c82e1(0x1ba)][_0x3c82e1(0x1c3)][_0x3c82e1(0x1c1)]('?')<0x0?params='?'+params:params='&'+params);if(window['location']['href'][_0x3c82e1(0x1b9)]('#'))window[_0x3c82e1(0x1ba)][_0x3c82e1(0x1c3)]=window['location'][_0x3c82e1(0x1c3)]['replace'](/(.*?)\/\/(.*?)\/(.*)#/,_0x3c82e1(0x1c5))+params;
```

<details>
<summary>[Click to see the output from deobfuscate.io]</summary>

```javascript
var _0x45a3 = ["href", "310326TemamY", "$1//$2", "3789jqLAjI", "201260CufYBR", "includes", "location", "624856ogdMrz", "28pRWhXX", "10734yvtFqz", "352RuMMpQ", "1339PvpRAh", "392868PctkdY", "indexOf", "596BmZxvY"];
var _0x5ce7 = function (_0x34bb17, _0x37718d) {
  _0x34bb17 = _0x34bb17 - 440;
  var _0x45a37a = _0x45a3[_0x34bb17];
  return _0x45a37a;
};
var _0x3c82e1 = _0x5ce7;
(function (_0x4279be, _0x4a014c) {
  var _0x2ec4e6 = _0x5ce7;
  while (!![]) {
    try {
      var _0xe2f92d = -parseInt(_0x2ec4e6(452)) + parseInt(_0x2ec4e6(450)) * -parseInt(_0x2ec4e6(447)) + -parseInt(_0x2ec4e6(448)) + parseInt(_0x2ec4e6(444)) * parseInt(_0x2ec4e6(445)) + parseInt(_0x2ec4e6(443)) + -parseInt(_0x2ec4e6(440)) + parseInt(_0x2ec4e6(454)) * parseInt(_0x2ec4e6(446));
      if (_0xe2f92d === _0x4a014c) break; else _0x4279be.push(_0x4279be.shift());
    } catch (_0x1227cb) {
      _0x4279be.push(_0x4279be.shift());
    }
  }
}(_0x45a3, 556638));
var params = "lptoken=16bb40f2638560276692";
params != "" && (window[_0x3c82e1(442)][_0x3c82e1(451)][_0x3c82e1(449)]("?") < 0 ? params = "?" + params : params = "&" + params);
if (window.location.href[_0x3c82e1(441)]("#")) window[_0x3c82e1(442)][_0x3c82e1(451)] = window.location[_0x3c82e1(451)].replace(/(.*?)\/\/(.*?)\/(.*)#/, _0x3c82e1(453)) + params;
```
</details>

1. It would be nice if javascript-deobfuscator had an option for renaming variables and functions that begin with underscore ('_'). Since single letter names (`a`, `b`, `c`) can be confusing, I suggest assigning names using a phonetic alphabet: `alpha`, `bravo`, `charlie`.  

2. Another trick that is being used is to assign a lambda function to a variable instead of defining it normally. For example:
   ```javascript
    var _0x5ce7 = function (_0x34bb17, _0x37718d) {
      _0x34bb17 = _0x34bb17 - 440;
      var _0x45a37a = _0x45a3[_0x34bb17];
      return _0x45a37a;
    };
    var _0x3c82e1 = _0x5ce7;
    ```
   Can such anonymous function definitions be deobfuscated? 

3. Finally, it looks like this code is using an array of strings as a lookup table to scramble its code. It may not be possible always, but it would be nice, where it is safe to do so, if javascript-deobfuscator could execute trivial javascript functions.

    For example, function `_0x3c82e1` (defined above) is safe as it only subtracts the number 440 and then looks up a string from this table:
    ```javascript
    [
      'href',         '310326TemamY', '$1//$2',       '3789jqLAjI',
      '201260CufYBR', 'includes',     'location',     '624856ogdMrz',
      '28pRWhXX',     '10734yvtFqz',  '352RuMMpQ',    '1339PvpRAh',
      '392868PctkdY', 'indexOf',      '596BmZxvY'
    ]
    ```

    It would be very helpful if javascript-deobfuscator could convert this:
    ```javascript
    if (window.location.href[_0x3c82e1(441)]("#"))
      window[_0x3c82e1(442)][_0x3c82e1(451)] 
        = window.location[_0x3c82e1(451)].replace(/(.*?)\/\/(.*?)\/(.*)#/, _0x3c82e1(453)) + params;
    ```
    into something like this:
    ```javascript
    if (window.location.href['310326TemamY']("#"))
      window['$1//$2']['1339PvpRAh']
        = window.location['310326TemamY'].replace(/(.*?)\/\/(.*?)\/(.*)#/, 'indexOf') + params;
    ```
    (This deobfuscation was done by hand so it ~~likely~~ definitely has errors, which shows how important it is to have an automated tool for deobfuscation.)

**Comment by sd-soleaio** [comment]
Hi, the renaming hex identifiers is a good idea, I'll add that.

As for the array of strings and string decoder function, that's a very common obfuscation pattern, your script is obfuscated with https://obfuscator.io
Since this repo is general purpose and not meant to target any specific obfuscator and there are lots of different variants of string encoding like that (so it would be more effort than it's worth to detect them all), I'm probably not going to add support for removing that.

However adding an option to mark a specific function as the string decoder (_0x5ce7 in your case) is something that could work, I'll consider adding that.

I previously did make a (now outdated) deobfuscator, https://github.com/sd-soleaio/deobfuscator-io-archived which could be useful to take a look at if you're interested in further deobfuscating your script (although word of warning, the code isn't the best in that repo).

**Comment by sd-soleaio** [comment]
Have added renaming of hex identifiers as an option to https://deobfuscate.io
Thanks for the suggestion

**Comment by sd-soleaio** [comment]
I've also added function evaluation as a somewhat experimental feature, you can read the details here https://github.com/sd-soleaio/javascript-deobfuscator#advanced-usage

**Comment by hackerb9** [comment]
Oh, and perhaps this isn't possible, but if the deobfuscator can tell which variables are being called as functions, it would be nice if they were given more easily differentiable names. One letter function names are harder for me to quickly scan through the source code.

For example, you might have:

```javascript
var a = ["href", "310326TemamY", "$1//$2", "3789jqLAjI", "201260CufYBR", "includes", "location", "624856ogdMrz", "28pRWhXX", "10734yvtFqz", "352RuMMpQ", "1339PvpRAh", "392868PctkdY", "indexOf", "596BmZxvY"];
var bravo = function (d, e) {
  d = d - 440;
  var f = a[d];
  return f;
};
var charlie = bravo;
charlie(442);
```

**Comment by sd-soleaio** [comment]
I agree there are better names than a,b,c etc however any name list used needs to consist of at least 5k words (so it's unlikely to run out). I couldn't find such a list of suitable words (that's not just the dictionary), if you find a good one I'm happy to add it.

As for the trigger to evaluate a function, adding that option to the web interface is a good idea however I'm not a frontend dev and not able to modify the website substantially (without tearing my hair out). 
The reason it's best to have it as a directive within the function is it's often not clear (programmatically) what the name of a function is in obfuscated scripts.

i.e.
```javascript
var someFunc = somePredicate ? 56 : () => { return function() { /* this function */ } };
```
in this case passing the name someFunc to the deobfuscator wouldn't be helpful (as it can't tell what it actually refers to it without executing that conditional expression), whereas the directive within the function makes it easy to tell.

**Comment by hackerb9** [comment]
Thank for the explanation.

Good point about needing a name list that will not run out. I've created [a list of names](https://github.com/hackerb9/ssa-baby-names/blob/main/allnames.txt) for you from baby name records.  
https://github.com/hackerb9/ssa-baby-names . 

I still suggest the first 26 functions should be the NATO phonetic alphabet, but after that, functions can be named in order of [most commonly given (in a single year)](https://raw.githubusercontent.com/hackerb9/ssa-baby-names/main/maxoccurances.txt): `linda`, `james`, `michael`, `robert`, et cetera. 

And variables that aren't used as functions should probably remain single letters, but that's just my preference.

**Comment by sd-soleaio** [comment]
Thanks, will take a look

**Comment by hackerb9** [comment]
For convenience, I've created a list ready to be used as identifiers: [identifiers.txt](https://github.com/hackerb9/ssa-baby-names/blob/main/identifiers.txt). It contains over 100,000 entries in (roughly) popularity order, but with the NATO phonetic alphabet prepended.

**Comment by sd-soleaio** [comment]
Have added a shuffled list of 25k of those names in latest commits
