### ISSUE TITLE
Crashed during function evaluate even though no execute directive used

### ISSUE THREAD

**Issue by sgkoishi** [ben-sb/javascript-deobfuscator#9]
```
/project/dist/modifications/execution/functionExecutor.js:62
                    const directive = node.body.directives.find((d) => d.rawValue.startsWith('#execute'));
                                                           ^

TypeError: Cannot read properties of undefined (reading 'find')
    at Controller.enter (/project/dist/modifications/execution/functionExecutor.js:62:60)
    at Controller.__execute (/project/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/project/node_modules/estraverse/estraverse.js:501:28)
    at Object.traverse (/project/node_modules/estraverse/estraverse.js:713:27)
    at FunctionExecutor.findExecutedFunctions (/project/dist/modifications/execution/functionExecutor.js:59:27)
    at FunctionExecutor.execute (/project/dist/modifications/execution/functionExecutor.js:47:14)
    at /project/dist/index.js:59:34
    at Array.forEach (<anonymous>)
    at Object.deobfuscate (/project/dist/index.js:59:19)
    at Object.<anonymous> (/project/dist/run.js:27:24)
```
[Sample formatted with esprima](https://github.com/ben-sb/javascript-deobfuscator/files/7836796/sample.txt)

**Comment by ben-sb** [comment]
Thanks, have published a fix in https://github.com/ben-sb/javascript-deobfuscator/commit/f958cc006ef2ad75f7ac83187e7fd4c90a5b6fc3
Can you let me know if that fixes it for your sample

**Comment by sgkoishi** [comment]
It is fixed!
<hr>
Is it possible to inline certain usage? For example, 

**Input**
```
const _0x38a2db = ['\x54\x6f\x74a\x6c', '\x6c\x6f\x67', '\x3a\x20'];
const _0x9b58d9 = function(_0x39ddb7) {
	return _0x38a2db[_0x39ddb7 + (-0x6d5 + 0x58 + 0x11 * 0x62)];
}, _0x498b9b = function(_0x48d808, _0x14da1e) {
    return _0x9b58d9(_0x48d808);
}, _0x34c7bc = function(_0x16af1d, _0x27a29e) {
    return _0x498b9b(_0x16af1d);
}
let total = 0x2 * 0x109e + -0xc * -0x16a + -0x3234;
for (let i = 0x1196 + 0x97b * 0x3 + -0x2e07; i < -0x95 * -0x38 + -0x1a75 + -0x619; i++) {
	total += i;
}
let decrypt = _0x34c7bc;
console[decrypt(-(0x1e7c + -0x1 * -0x1367 + 0x2ef * -0x11))](decrypt(-(0x1020 + 0x253 + 0x7 * -0x2a2)) + decrypt(-(0x12c5 + -0x1887 + -0x1 * -0x5c5)) + total);
```
**Expected**
```
let total = 0;
for (let i = 0; i < 10; i++) {
  total += i;
}
console.log("Total: " + total);
```
**Actual**
```
const jeiden = ["Total", "log", ": "];
let total = 0;
for (let i = 0; i < 10; i++) {
  total += i;
}
let decrypt = _0x34c7bc;
console[decrypt(-4)](decrypt(-5) + decrypt(-3) + total);
```

I'm currently using [willnode/deobfuscator's RegEx solution](https://github.com/willnode/deobfuscator/blob/master/src/index.js#L153-L186) to manually inline them - not perfect but works!

**Comment by sgkoishi** [comment]
Also, in some cases string literals were not fully simplified:
`console.log("a" + "b" + '"' + "a" + "b")` were transformed to `console.log("ab" + '"' + "a" + "b");`

**Comment by ben-sb** [comment]
Yes, I'll add storing all references to proxy functions to my to do list.
As for the string literals not being fully simplified, can you provide a sample in which this occurs?

**Comment by sgkoishi** [comment]
> Yes, I'll add storing all references to proxy functions to my to do list. As for the string literals not being fully simplified, can you provide a sample in which this occurs?

![image](https://user-images.githubusercontent.com/9637711/148799007-090a54a1-0635-4951-8156-0d77f265684b.png)
`console.log("a" + "b" + '"' + "a" + "b")`
Here it is!

**Comment by ben-sb** [comment]
Have fixed that in https://github.com/ben-sb/javascript-deobfuscator/commit/7c9fbfa0147746651ec7154366e0aa63bc4f348e
Was just a simple bug to do with the double quotes

**Comment by sgkoishi** [comment]
Great thanks!

<hr>

~~Actually the third problem,~~ [spread syntax (three dots)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) is not supported by the third party package `estraverse`:
```
> javascript-deobfuscator@1.0.0 start
> tsc && node dist/run.js

/project/node_modules/estraverse/estraverse.js:521
                        throw new Error('Unknown node type ' + nodeType + '.');
                        ^

Error: Unknown node type SpreadProperty.
    at Controller.traverse (/project/node_modules/estraverse/estraverse.js:521:31)
    at Object.traverse (/project/node_modules/estraverse/estraverse.js:713:27)
    at FunctionExecutor.findExecutedFunctions (/project/dist/modifications/execution/functionExecutor.js:59:27)
    at FunctionExecutor.execute (/project/dist/modifications/execution/functionExecutor.js:47:14)
    at /project/dist/index.js:59:34
    at Array.forEach (<anonymous>)
    at Object.deobfuscate (/project/dist/index.js:59:19)
    at Object.<anonymous> (/project/dist/run.js:27:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Input**
```
let a = { key: "value" };
let b = { ...a };
```
It is not a big problem - people could also manually replace them with random placeholder without breaking the logic

**Comment by ben-sb** [comment]
Thanks for letting me know, the problem was actually with the shift-spec module not being up to date, I employed a hacky solution to force estraverse to use the up to date spec in https://github.com/ben-sb/javascript-deobfuscator/commit/e8daa25756f3582f38785d1effdf2845038f8c65

Most of my projects nowadays use babel as the AST rather than Shift as it's more actively developed, at some point I rewrite this repo to use babel to avoid something like this happening again.

**Comment by ben-sb** [comment]
> It is fixed!
> 
> Is it possible to inline certain usage? For example,
> **Input**
> 
> ```
> const _0x38a2db = ['\x54\x6f\x74a\x6c', '\x6c\x6f\x67', '\x3a\x20'];
> const _0x9b58d9 = function(_0x39ddb7) {
> 	return _0x38a2db[_0x39ddb7 + (-0x6d5 + 0x58 + 0x11 * 0x62)];
> }, _0x498b9b = function(_0x48d808, _0x14da1e) {
>     return _0x9b58d9(_0x48d808);
> }, _0x34c7bc = function(_0x16af1d, _0x27a29e) {
>     return _0x498b9b(_0x16af1d);
> }
> let total = 0x2 * 0x109e + -0xc * -0x16a + -0x3234;
> for (let i = 0x1196 + 0x97b * 0x3 + -0x2e07; i < -0x95 * -0x38 + -0x1a75 + -0x619; i++) {
> 	total += i;
> }
> let decrypt = _0x34c7bc;
> console[decrypt(-(0x1e7c + -0x1 * -0x1367 + 0x2ef * -0x11))](decrypt(-(0x1020 + 0x253 + 0x7 * -0x2a2)) + decrypt(-(0x12c5 + -0x1887 + -0x1 * -0x5c5)) + total);
> ```
> 
> **Expected**
> 
> ```
> let total = 0;
> for (let i = 0; i < 10; i++) {
>   total += i;
> }
> console.log("Total: " + total);
> ```
> 
> **Actual**
> 
> ```
> const jeiden = ["Total", "log", ": "];
> let total = 0;
> for (let i = 0; i < 10; i++) {
>   total += i;
> }
> let decrypt = _0x34c7bc;
> console[decrypt(-4)](decrypt(-5) + decrypt(-3) + total);
> ```
> 
> I'm currently using [willnode/deobfuscator's RegEx solution](https://github.com/willnode/deobfuscator/blob/master/src/index.js#L153-L186) to manually inline them - not perfect but works!

I've added support for proxy function reassignments in https://github.com/ben-sb/javascript-deobfuscator/commit/bd7564db5d87e07bd39d5974cfe4f5f6c3e621b6
